import Head from 'next/head';

const AllRecipesPage = () => {
  return (
    <>
      <Head>
        <title>Recipes | CookBooK</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>RECIPES PAGE</h1>
    </>
  );
};

export default AllRecipesPage;
