import Head from 'next/head';
import React, { useEffect } from 'react';
import { GetServerSidePropsContext } from 'next';
import { useSession, getSession } from 'next-auth/react';
import { Session } from 'next-auth';
import { useRouter } from 'next/router';
import UserProfile from '@/components/user-profile/UserProfile';

const Profile = () => {
  const router = useRouter();
  const { data: session } = useSession();

  if (!session) {
    router.push('/signin');
  }

  return (
    <>
      <Head>
        <title>Recipes | CookBooK</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserProfile />
    </>
  );
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const session = await getSession({
    req: context.req,
  });

  if (!session) {
    return {
      redirect: {
        destination: '/signin',
        permanent: true,
      },
    };
  }

  return {
    props: { session },
  };
}

export default Profile;
