import { Button } from '@mui/material';
import Head from 'next/head';
import NextLink from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Sw33t home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>itt igazából nem sok minden van. menj inkább recepteket nézni</h2>
        <Button component={NextLink} href="/recipes" variant="contained">
          na jó, lássuk
        </Button>
      </main>
    </>
  );
}
